// <auto-generated />
using System;
using AnagramSolver.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnagramSolver.EF.CodeFirst.Migrations
{
    [DbContext(typeof(AnagramContext))]
    [Migration("20200817065303_AddValidation")]
    partial class AddValidation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.7.20365.15");

            modelBuilder.Entity("AnagramSolver.Models.CachedWordEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("SearchWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserLogEntityID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserLogEntityID");

                    b.ToTable("CachedWordEntities");
                });

            modelBuilder.Entity("AnagramSolver.Models.UserLogEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UserLogEntities");
                });

            modelBuilder.Entity("AnagramSolver.Models.WordEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CachedWordEntityID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CachedWordEntityID");

                    b.ToTable("WordEntities");
                });

            modelBuilder.Entity("AnagramSolver.Models.CachedWordEntity", b =>
                {
                    b.HasOne("AnagramSolver.Models.UserLogEntity", null)
                        .WithMany("CachedWordEntity")
                        .HasForeignKey("UserLogEntityID");
                });

            modelBuilder.Entity("AnagramSolver.Models.WordEntity", b =>
                {
                    b.HasOne("AnagramSolver.Models.CachedWordEntity", null)
                        .WithMany("WordEntity")
                        .HasForeignKey("CachedWordEntityID");
                });
#pragma warning restore 612, 618
        }
    }
}
